# Generated by Django 6.0.5 on 2026-06-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0020_m3uaccount_proxy_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='cron_expression',
            field=models.CharField(blank=True, help_text='Cron expression for periodic sync', max_length=100, null=True),
        ),
    ]
