# Generated by Django 6.0.5 on 2026-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('server_type', models.CharField(choices=[('plex', 'Plex'), ('emby', 'Emby'), ('jellyfin', 'Jellyfin')], max_length=20)),
                ('base_url', models.URLField()),
                ('api_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_properties', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
