# Generated by Django 6.0.5 on 2026-06-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0023_epgsource_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgsource',
            name='cron_expression',
            field=models.CharField(blank=True, help_text='Cron expression for periodic sync', max_length=100, null=True),
        ),
    ]
