# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0024_remove_epgsource_api_key_epgsource_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgsource',
            name='time_offset_minutes',
            field=models.IntegerField(default=0, help_text='Global time offset applied to all programs from this source during parsing'),
        ),
    ]
