# Generated by Django 6.0.5 on 2026-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argusflix_manager_channels', '0037_auto_sync_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this stream is active and working (not marked broken by validation).'),
        ),
    ]
