# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0038_stream_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='epg_time_offset_minutes',
            field=models.IntegerField(default=0, help_text='Time offset applied to EPG programs during playback and API responses for this specific channel'),
        ),
    ]
