# Generated by Django 6.0.5 on 2026-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0019_m3uaccountprofile_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='proxy_url',
            field=models.CharField(blank=True, default='', help_text='Optional SOCKS5H/HTTP proxy URL for this account (e.g. socks5h://user:pass@host:port).', max_length=1000),
        ),
        migrations.AddField(
            model_name='m3uaccount',
            name='skip_ssl_verification',
            field=models.BooleanField(default=False, help_text='Bypass SSL/TLS certificate validation.'),
        ),
        migrations.AddField(
            model_name='m3uaccount',
            name='timeout',
            field=models.PositiveIntegerField(default=30, help_text='HTTP request timeout in seconds (default: 30).'),
        ),
    ]
