# Generated by Django 6.0.5 on 2026-06-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0022_alter_epgdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgsource',
            name='group_name',
            field=models.CharField(blank=True, help_text='Group EPG sources together (e.g. by country) to merge them in channel mapping UI', max_length=255, null=True),
        ),
    ]
