# Generated by Django 6.0.5 on 2026-06-05 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatcharr_channels', '0037_auto_sync_overhaul'),
        ('vod', '0004_m3uepisoderelation_series_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_properties', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPlaylistLiveMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('channel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcharr_channels.channelgroup')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_mappings', to='output.customplaylist')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('playlist', 'channel_group')},
            },
        ),
        migrations.CreateModel(
            name='CustomPlaylistVODMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vod_mappings', to='output.customplaylist')),
                ('vod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vod.vodcategory')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('playlist', 'vod_category')},
            },
        ),
    ]
